name: yi-keymap-vim
version: 0.15.0
synopsis: Vim keymap for Yi editor
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

data-files:
  - tests/vimtests/*/*.test

dependencies:
    - attoparsec
    - base >= 4.8 && < 5
    - binary
    - containers
    - data-default
    - directory
    - filepath
    - Hclip
    - microlens-platform
    - mtl
    - oo-prototypes
    - pointedlist
    - safe
    - semigroups
    - text
    - transformers-base
    - unordered-containers
    - yi-core >= 0.13.7
    - yi-rope

library:
    source-dirs: src
    exposed-modules:
        - Yi.Config.Default.Vim
        - Yi.Keymap.Vim
        - Yi.Keymap.Vim.Common
        - Yi.Keymap.Vim.Digraph
        - Yi.Keymap.Vim.Eval
        - Yi.Keymap.Vim.EventUtils
        - Yi.Keymap.Vim.Ex
        - Yi.Keymap.Vim.Ex.Commands.Buffer
        - Yi.Keymap.Vim.Ex.Commands.BufferDelete
        - Yi.Keymap.Vim.Ex.Commands.Buffers
        - Yi.Keymap.Vim.Ex.Commands.Cabal
        - Yi.Keymap.Vim.Ex.Commands.Common
        - Yi.Keymap.Vim.Ex.Commands.Copy
        - Yi.Keymap.Vim.Ex.Commands.Delete
        - Yi.Keymap.Vim.Ex.Commands.Edit
        - Yi.Keymap.Vim.Ex.Commands.Global
        - Yi.Keymap.Vim.Ex.Commands.GotoLine
        - Yi.Keymap.Vim.Ex.Commands.Help
        - Yi.Keymap.Vim.Ex.Commands.Make
        - Yi.Keymap.Vim.Ex.Commands.Nohl
        - Yi.Keymap.Vim.Ex.Commands.Paste
        - Yi.Keymap.Vim.Ex.Commands.Quit
        - Yi.Keymap.Vim.Ex.Commands.Read
        - Yi.Keymap.Vim.Ex.Commands.Shell
        - Yi.Keymap.Vim.Ex.Commands.Sort
        - Yi.Keymap.Vim.Ex.Commands.Substitute
        - Yi.Keymap.Vim.Ex.Commands.Tag
        - Yi.Keymap.Vim.Ex.Commands.Undo
        - Yi.Keymap.Vim.Ex.Commands.Write
        - Yi.Keymap.Vim.Ex.Commands.Yi
        - Yi.Keymap.Vim.Ex.Commands.Registers
        - Yi.Keymap.Vim.Ex.Eval
        - Yi.Keymap.Vim.Ex.Types
        - Yi.Keymap.Vim.ExMap
        - Yi.Keymap.Vim.InsertMap
        - Yi.Keymap.Vim.MatchResult
        - Yi.Keymap.Vim.Motion
        - Yi.Keymap.Vim.NormalMap
        - Yi.Keymap.Vim.NormalOperatorPendingMap
        - Yi.Keymap.Vim.Operator
        - Yi.Keymap.Vim.ReplaceMap
        - Yi.Keymap.Vim.ReplaceSingleCharMap
        - Yi.Keymap.Vim.Search
        - Yi.Keymap.Vim.SearchMotionMap
        - Yi.Keymap.Vim.StateUtils
        - Yi.Keymap.Vim.StyledRegion
        - Yi.Keymap.Vim.Tag
        - Yi.Keymap.Vim.TextObject
        - Yi.Keymap.Vim.Utils
        - Yi.Keymap.Vim.VisualMap

tests:
    spec:
        main: TestSuite.hs
        source-dirs:
            - tests
        dependencies:
            - tasty
            - tasty-hunit
            - QuickCheck
            - tasty-quickcheck
            - yi-core
            - yi-keymap-vim
