name: yi-vim-pango-static
version: 0.16.0
license: GPL-2
maintainer: Yi developers <yi-devel@googlegroups.com>
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans -threaded

dependencies:
    - base >= 4.8 && < 5
    - microlens-platform
    - mtl
    - yi-core >= 0.14
    - yi-frontend-pango >= 0.14
    - yi-keymap-vim >= 0.14
    - yi-misc-modes >= 0.14
    - yi-mode-haskell >= 0.14
    - yi-rope >= 0.9

executables:
    yi-vim-pango:
        main: Main.hs
        source-dirs: .
