name: yi-misc-modes
version: 0.15.0
synopsis: Yi editor miscellaneous modes
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

dependencies:
    - array
    - base >= 4.8 && < 5
    - binary >= 0.7
    - data-default
    - filepath
    - microlens-platform
    - semigroups
    - text
    - yi-core
    - yi-rope
library:
    source-dirs: src
    exposed-modules:
      - Yi.Config.Default.MiscModes
      - Yi.Modes
      - Yi.Mode.Buffers