flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-dynamic-configuration
- yi-frontend-pango
- yi-frontend-vty
- yi-fuzzy-open
- yi-ireader
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-misc-modes
- yi-snippet
- example-configs/yi-all-static
- example-configs/yi-emacs-vty-static
- example-configs/yi-emacs-vty-dynamic
- example-configs/yi-vim-colemak-vty-dynamic
- example-configs/yi-vim-pango-dynamic
- example-configs/yi-vim-pango-static
- example-configs/yi-vim-vty-dynamic
- example-configs/yi-vim-vty-static
resolver: lts-8.18
build:
 library-profiling: false
 executable-profiling: false

# needed for macOS
# flags:
#   gtk:
#     have-quartz-gtk: true