flags: {}
packages:
- yi-core
- yi-frontend-vty
# - yi-frontend-pango
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-mode-haskell
- yi-mode-javascript
- yi-stock-modes
- yi-language
- yi
extra-deps:
- Hclip-3.0.0.3
# - gconf-0.13.1.0
resolver: lts-6.5
nix:
    shell-file: shell.nix