flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-dynamic-configuration
- yi-frontend-pango
- yi-frontend-vty
- yi-fuzzy-open
- yi-ireader
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-misc-modes
- yi-snippet
extra-deps: []
resolver: lts-8.18
build:
 library-profiling: false
 executable-profiling: false

# needed for macOS
# flags:
#   gtk:
#     have-quartz-gtk: true