name: yi-ireader
version: 0.15.0
synopsis: Yi editor incremental reader
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

dependencies:
    - base >= 4.8 && < 5
    - bytestring
    - binary >= 0.7
    - containers
    - data-default
    - microlens-platform
    - text
    - yi-core
    - yi-rope

library:
    source-dirs: src
    exposed-modules:
        - Yi.Mode.IReader
        - Yi.IReader