name: yi-all-static
version: 0.13.5
license: GPL-2
maintainer: Yi developers <yi-devel@googlegroups.com>
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans -threaded

flags:
  vty:
    description: Include the vty (CLI) frontend
    manual: True
    default: True
  pango:
    description: Include the pango (GUI) frontend
    manual: True
    default: True
  vim:
    description: Include the vim keymap
    manual: True
    default: True
  emacs:
    description: Include the emacs keymap
    manual: True
    default: True

dependencies:
    - base >= 4.8 && < 5
    - microlens-platform
    - mtl
    - optparse-applicative >= 0.13.0.0
    - yi-core
    - yi-misc-modes
    - yi-mode-haskell
    - yi-mode-javascript
    - yi-rope

when:
  - condition: flag(vty)
    dependencies: yi-frontend-vty
    cpp-options: -DVTY
  - condition: flag(pango)
    dependencies: yi-frontend-pango
    cpp-options: -DPANGO
  - condition: flag(vim)
    dependencies: yi-keymap-vim
    cpp-options: -DVIM
  - condition: flag(emacs)
    dependencies: yi-keymap-emacs
    cpp-options: -DEMACS

executables:
    yi:
        main: Main.hs
        source-dirs: .
