name: yi
version: 0.13.7
synopsis: Yi editor
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans -threaded -eventlog -rtsopts

flags:
  vty:
    description: Include the vty (CLI) frontend
    manual: True
    default: True
  pango:
    description: Include the pango (GUI) frontend
    manual: True
    default: True
  vim:
    description: Include the vim keymap
    manual: True
    default: True
  emacs:
    description: Include the emacs keymap
    manual: True
    default: True

dependencies:
    - base >= 4.8 && < 5
    - microlens-platform >= 0.3.4.0
    - mtl >= 2.2.1
    - optparse-applicative >= 0.13.0.0
    - yi-core >= 0.13.0.1
    - yi-misc-modes >= 0.13.0.1
    - yi-mode-haskell >= 0.13.0.1
    - yi-mode-javascript >= 0.13.0.1
    - yi-rope >= 0.7.0.1

when:
  - condition: flag(vty)
    dependencies: yi-frontend-vty
    cpp-options: -DVTY
  - condition: flag(pango)
    dependencies: yi-frontend-pango
    cpp-options: -DPANGO
  - condition: flag(vim)
    dependencies: yi-keymap-vim
    cpp-options: -DVIM
  - condition: flag(emacs)
    dependencies: yi-keymap-emacs
    cpp-options: -DEMACS

executables:
    yi:
        main: Main.hs
        source-dirs: .
