name: yi-fuzzy-open
version: 0.15.0
synopsis: Fuzzy open plugin for yi
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi
description: This plugin tries to do what ctrl-p does for vim and helm does for emacs.

ghc-options: -Wall -ferror-spans

dependencies:
    - base >= 4.8 && < 5
    - binary >= 0.7.5
    - containers >= 0.5.6
    - data-default >= 0.5
    - directory >= 1.2.2
    - filepath >= 1.4.0
    - mtl >= 2.2
    - text >= 1.2
    - transformers-base >= 0.4.4
    - vector >= 0.11
    - yi-core >= 0.15.0
    - yi-rope >= 0.7

library:
  source-dirs: src
  exposed-modules:
  - Yi.Fuzzy