.TH YI 1 2005-03-27 "yi version 0.1" "User Manual"

.SH NAME
yi \- text editor extensible in Haskell

.SH SYNOPSIS
.B yi 
[\fIOPTION\fR] [\fIFILENAME\fR]

.SH DESCRIPTION
.ds c \fIyi\fP
\*c is a text editor written and extensible in Haskell. Consult the html
documentation for a full description of its behaviour.
.PP
.TP
.B \-B libdir \-\-libdir=libdir
Path to runtime libraries
.TP
.B \-l num \-\-line=num
Start on given line number
.TP
.B \-\-as=editor
Start with key bindings of given editor.
.TP
.B \-V \-\-version
Show version information
.TP
.B \-h \-\-help
Show help message

.SH BUGS
Bug reports, and any other feedback, should be sent to
Don Stewart <dons@cse.unsw.edu.au>
.SH COPYRIGHT
Copyright \(co 2004-2005 Don Stewart,
except for components derived from Riot <http://iki.fi/tuomov/riot/>,
Copyright \(co Tuomo Valkonen.
.PP
Yi is released under the terms of the GPL.
.SH "SEE ALSO"
.BR vi (1)

.SH AUTHOR

This manual page was written by Don Stewart, based on that of cpphs,
written by Ian Lynagh <igloo@debian.org>.

