.TH YI 1 2008-10-22 "yi version 0.1" "User Manual"

.SH NAME
yi \- text editor extensible in Haskell

.SH SYNOPSIS
.B yi
[\fIOPTION\fR] [\fIFILENAME\fR]

.SH DESCRIPTION
.ds c \fIYi\fP
\*c is a text editor written and extensible in Haskell. Consult the html
documentation for a full description of its behaviour.
.PP
.TP
.B \-\-selfcheck
Run self-checks
.TP
.B \-f frontend \-\-frontend=frontend
Select frontend (one of vty, gtk, pango, cocoa).
.TP
.B \-y config \-\-config\-file=config
Specify a configuration file.
.TP
.B \-V \-\-version
Show version information
.TP
.B \-h \-\-help
Show help message.
.TP
.B \-\-debug
Write debug information in a log file.
.TP
.B \-l num \-\-line=num
Start on given line number
.TP
.B \-\-as=editor
Start with key bindings of given editor.
.TP
.B \-\-recompile\-force
Force recompile of custom Yi before starting.
.TP
.B \-\-resume
Resume execution of Yi from previous state.
.TP
.B \-\-recompile
Recompile custom Yi if required then exit.

.SH FILES
It can be configured in ~/.config/yi/yi.hs; consult the html
documentation.

.SH BUGS
Bug reports should be posted to the Google issue tracker
<http://code.google.com/p/yi-editor/issues/>. Other suggestions or ideas may
be posted to the yi-devel <yi-devel@googlegroups.com> mailing list.
.SH COPYRIGHT
Copyright \(co 2004-2005 Don Stewart,
except for components derived from Riot <http://iki.fi/tuomov/riot/>,
Copyright \(co Tuomo Valkonen.
.PP
Yi is released under the terms of the GPL.
.SH "SEE ALSO"
.BR vi (1)

.SH AUTHOR

Yi is developed by a team of many developers, currently lead by Jean-Philippe
Bernardy.