name:                yi-dynamic-configuration
version: 0.15.0
synopsis: Dynamic configuration support for Yi
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

dependencies:
- base >= 4.8 && < 5
- dyre >= 0.8.11
- yi-core >= 0.15.0
- transformers-base
- mtl >= 0.1.0.1
- microlens-platform
- text >= 1.0
- yi-rope >= 0.7.0.2

library:
  source-dirs: src
  exposed-modules:
  - Yi.Boot
  - Yi.Boot.Internal