name: yi-emacs-vty-dynamic
version: 0.15.0
license: GPL-2
maintainer: Yi developers <yi-devel@googlegroups.com>
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans -threaded -O2

dependencies:
    - base >= 4.8 && < 5
    - yi-core >= 0.15
    - yi-dynamic-configuration
    - yi-keymap-emacs
    - yi-frontend-vty
    - yi-misc-modes
    - yi-rope
    - oo-prototypes
    - microlens-platform

executables:
    yi:
        main: yi.hs
        source-dirs: .