packages:
  - .
  - location: '../..'
    extra-dep: true
    subdirs:
     - yi-core
     - yi-keymap-emacs
     - yi-frontend-vty
     - yi-mode-haskell
     - yi-mode-javascript
     - yi-misc-modes
  - location:
      git: https://github.com/willdonnelly/dyre.git
      commit: 971e2eccce29edd820c776ac61593a4ea3fd1fdb
    extra-dep: true

resolver: nightly-2016-08-06
