
all: yi+lambda-fat-16.png yi+lambda-fat-32.png yi+lambda-fat-64.png yi+lambda-fat-128.png

yi+lambda-fat.%.png: yi+lambda-fat.svg
	 convert -background "#0000" 1.0 -resize $*x$* yi+lambda-fat.svg $@
