name: yi-keymap-emacs
version: 0.13.5
synopsis: Emacs keymap for Yi editor
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

dependencies:
    - base >= 4.8 && < 5
    - containers
    - filepath
    - Hclip
    - microlens-platform
    - mtl
    - oo-prototypes
    - semigroups
    - text
    - transformers-base
    - yi-core
    - yi-misc-modes
    - yi-language
    - yi-rope

library:
    source-dirs: src
    exposed-modules:
        - Yi.Config.Default.Emacs
        - Yi.Keymap.Emacs
        - Yi.Keymap.Emacs.KillRing
        - Yi.Keymap.Emacs.Utils