name: yi-core
version: 0.13.7
synopsis: Yi editor core library
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

flags:
  hint:
    description: Include hint (haskell interpreter) in yi
    manual: True
    default: False
  profiling:
    description:
      Runtime binary will be compiled with profiling and RTS
      options enabled.
    manual: True
    default: False
  eventlog:
    description:
      Runtime binary will be compiled with eventlog and RTS
      options enabled.
    manual: True
    default: False
  testing:
    description: bake-in the self-checks
    manual: True
    default: False

dependencies:
    - base >= 4.8 && < 5
    - array
    - attoparsec
    - binary >= 0.7
    - bytestring >= 0.9.1
    - containers
    - data-default
    - directory
    - dlist >= 0.4.1
    - dynamic-state >= 0.1.0.5
    - dyre >= 0.8.11
    - exceptions
    - filepath >= 1.1
    - hashable >= 1.1.2.5
    - Hclip >= 3
    - ListLike >= 4.5
    - microlens-platform
    - mtl >= 0.1.0.1
    - old-locale
    - oo-prototypes
    - parsec >= 3.0
    - pointedlist >= 0.5
    - process >= 1.0.1.1
    - process-extras >= 0.3.3.8
    - safe >= 0.3.4
    - semigroups
    - split >= 0.2
    - text >= 1.1.1.3
    - text-icu >= 0.7
    - time >= 1.1
    - transformers-base
    - unix-compat >= 0.1
    - unordered-containers >= 0.1.3
    - word-trie >= 0.2.0.4
    - xdg-basedir >= 0.2.1
    - yi-language >= 0.1.1.0
    - yi-rope >= 0.7.0.0
when:
  - condition: os(win32)
    then:
      dependencies:
        - Win32
    else:
      dependencies:
        - unix



library:
    source-dirs: src

    when:
      - condition: flag(profiling)
        cpp-options: -DPROFILING

      - condition: flag(eventlog)
        cpp-options: -DEVENTLOG
        ghc-options: -Wall -fno-warn-orphans -eventlog

      - condition: flag(hint)
        cpp-options: -DHINT
        dependencies:
          - hint > 0.3.1

      - condition: flag(testing)
        cpp-options: -DTESTING
        dependencies:
          - QuickCheck >= 2.7
          - random

    ghc-options: -Wall -fno-warn-orphans -ferror-spans

    exposed-modules:
        - Yi
        - Yi.Boot
        - Yi.Boot.Internal
        - Yi.Buffer
        - Yi.Buffer.Adjusted
        - Yi.Buffer.HighLevel
        - Yi.Buffer.Indent
        - Yi.Buffer.Normal
        - Yi.Buffer.Misc
        - Yi.Buffer.Region
        - Yi.Buffer.TextUnit
        - Yi.Buffer.Undo
        - Yi.Command
        - Yi.Command.Help
        - Yi.Completion
        - Yi.CompletionTree
        - Yi.Config
        - Yi.Config.Default
        - Yi.Config.Misc
        - Yi.Config.Lens
        - Yi.Config.Simple
        - Yi.Config.Simple.Types
        - Yi.Core
        - Yi.Debug
        - Yi.Dired
        - Yi.Editor
        - Yi.Eval
        - Yi.Event
        - Yi.File
        - Yi.History
        - Yi.Hoogle
        - Yi.Hooks
        - Yi.IncrementalParse
        - Yi.Interact
        - Yi.JumpList
        - Yi.Keymap
        - Yi.Keymap.Keys
        - Yi.KillRing
        - Yi.Layout
        - Yi.Main
        - Yi.MiniBuffer
        - Yi.Misc
        - Yi.Mode.Common
        - Yi.Mode.Compilation
        - Yi.Mode.Interactive
        - Yi.Monad
        - Yi.Option
        - Yi.Paths
        - Yi.PersistentState
        - Yi.Process
        - Yi.Rectangle
        - Yi.Search
        - Yi.Search.Internal
        - Yi.String
        - Yi.Syntax.Driver
        - Yi.Syntax.Layout
        - Yi.Syntax.OnlineTree
        - Yi.Syntax.Tree
        - Yi.Tab
        - Yi.Tag
        - Yi.TextCompletion
        - Yi.Types
        - Yi.UI.Common
        - Yi.UI.SimpleLayout
        - Yi.UI.TabBar
        - Yi.UI.Utils
        - Yi.Window
        - System.FriendlyPath
        - Parser.Incremental

tests:
  tasty:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - quickcheck-text
      - yi-core
      - text
      - containers

benchmarks:
  all:
    main: Bench.hs
    source-dirs: bench
    ghc-options: -Wall -ferror-spans -rtsopts
    dependencies:
      - yi-core
      - criterion
      - deepseq
