name: yi-emacs-vty-static
version: 0.15.0
license: GPL-2
maintainer: Yi developers <yi-devel@googlegroups.com>
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans -threaded

dependencies:
    - base >= 4.8 && < 5
    - microlens-platform
    - mtl
    - yi-core
    - yi-frontend-vty
    - yi-keymap-emacs
    - yi-misc-modes
    - yi-rope

executables:
    yi-emacs-vty:
        main: Main.hs
        source-dirs: .
