packages:
  - .
  - location: '../..'
    extra-dep: true
    subdirs:
     - yi-core
     - yi-keymap-vim
     - yi-frontend-pango
     - yi-misc-modes
  - location:
      git: https://github.com/willdonnelly/dyre.git
      commit: 971e2eccce29edd820c776ac61593a4ea3fd1fdb
    extra-dep: true

resolver: lts-8.18
extra-deps: []