name: yi-frontend-vty
version: 0.13.2
synopsis: Vty frontend for Yi editor
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

dependencies:
    - base >= 4.8 && < 5
    - containers
    - data-default
    - dlist
    - microlens-platform
    - pointedlist
    - stm >= 2.2
    - text
    - vty >= 5.4
    - yi-core
    - yi-language

library:
    source-dirs: src
    exposed-modules:
        - Yi.Config.Default.Vty
        - Yi.Frontend.Vty
        - Yi.Frontend.Vty.Conversions